# Site settings
title: Let's go places!
header-img: img/home.png
email: guillermot@spiceworks.com
description: "Every human has a finite number of heartbeats. I don't intend to waste any of mine."
baseurl: ""
url: "http://yourdomain.com"
github_username:  atxmemo
facebook_username:  guillermo.terrazas.7

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
